# get film list
GET http://localhost:4000/films HTTP/1.1
Content-Type: application/json
###

# get film by filmId
GET http://localhost:4000/films/6476760e8562478c829d5b41 HTTP/1.1
Content-Type: application/json
###

# get promo film
GET http://localhost:4000/films/promo HTTP/1.1
Content-Type: application/json
###

# change film by filmId
PUT http://localhost:4000/films/649c63516a332d7bda5711db HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItdGVzdEBtYWlsLmNvbSIsImlkIjoiNjQ5YzEyMjgzZTVjZDA5OTEyM2YxYjcxIiwiaWF0IjoxNjg3OTU5NzE1LCJleHAiOjE2ODgxMzI1MTV9.bWbkjoGrEvGCygW1xdjPXSGXD2Da7nRZBq_sLzL3BBc

{
  "duration": 50
}
###

#create new film
POST http://localhost:4000/films HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItdGVzdEBtYWlsLmNvbSIsImlkIjoiNjQ5YzEyMjgzZTVjZDA5OTEyM2YxYjcxIiwiaWF0IjoxNjg3OTU5NzE1LCJleHAiOjE2ODgxMzI1MTV9.bWbkjoGrEvGCygW1xdjPXSGXD2Da7nRZBq_sLzL3BBc

{
  "title": "Film title 11",
  "description": "Film description Film description Film description Film description Film description ",
  "publicationDate": "2022-05-12T11:56:37.573Z",
  "genre": ["thriller", "comedy"],
  "realiseDate": "2022-05-12T11:56:37.573Z",
  "previewVideo": "http://previewVideo.com",
  "videoLink": "http://videoLink.com",
  "actors": ["Bill M", "Michael St"],
  "director": "director",
  "duration": 120,
  "poster": "posterImage.jpg",
  "backgroundImage": "backgroundImage.jpg",
  "backgroundColor": "#FFFFFF"
}
###

# get films by genre
GET http://localhost:4000/films/genre/thriller HTTP/1.1
Content-Type: application/json
###

# delete films by filmID
DELETE http://localhost:4000/films/6476760e8562478c829d5b53 HTTP/1.1
Content-Type: application/json
###
